CREATE TABLE smash_challenge (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  created INT UNSIGNED NOT NULL,
  ladder_id VARCHAR(30) NOT NULL,
  from_id INT UNSIGNED NOT NULL,
  to_id INT UNSIGNED NOT NULL
)
