CREATE TABLE smash_player (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  userName VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(80) NULL,
  name VARCHAR(80) NULL,
  created INT UNSIGNED NOT NULL,
  modified INT UNSIGNED NOT NULL
) CHARACTER SET=utf8;
